import { z } from "zod";
import { GRADES } from "@/lib/config";

/* ───────── Phone ───────── */

const EG_MOBILE = /^01[0125]\d{8}$/;

/** Converts Arabic-Indic digits, strips separators and country codes → local 11-digit format. */
export function normalizePhone(input: string): string {
  let s = input
    .replace(/[\u0660-\u0669]/g, (d) => String(d.charCodeAt(0) - 0x0660))
    .replace(/[\u06F0-\u06F9]/g, (d) => String(d.charCodeAt(0) - 0x06f0))
    .replace(/[\s\-().]/g, "");
  if (s.startsWith("+20")) s = "0" + s.slice(3);
  else if (s.startsWith("0020")) s = "0" + s.slice(4);
  else if (/^20\d{10}$/.test(s)) s = "0" + s.slice(2);
  else if (/^1[0125]\d{8}$/.test(s)) s = "0" + s;
  return s;
}

export function isValidPhone(value: string): boolean {
  return EG_MOBILE.test(value);
}

const phoneField = (label: string) =>
  z
    .string({ required_error: `${label} مطلوب` })
    .trim()
    .min(1, `${label} مطلوب`)
    .transform(normalizePhone)
    .refine(isValidPhone, "رقم الهاتف غير صحيح. مثال: 01012345678");

/* ───────── Names ───────── */

const NAME_CHARS = /^[\p{L}\p{M}][\p{L}\p{M}\s'.-]*$/u;
const squash = (s: string) => s.replace(/\s+/g, " ");

export const studentNameSchema = z
  .string({ required_error: "الاسم مطلوب" })
  .trim()
  .min(1, "الاسم مطلوب")
  .transform(squash)
  .pipe(
    z
      .string()
      .min(6, "الاسم قصير جداً")
      .max(100, "الاسم طويل جداً")
      .refine((v) => v.split(" ").length >= 3, "اكتب الاسم الرباعي كاملاً")
      .refine((v) => NAME_CHARS.test(v), "الاسم يجب أن يحتوي على حروف فقط"),
  );

export const guardianNameSchema = z
  .string({ required_error: "اسم ولي الأمر مطلوب" })
  .trim()
  .min(1, "اسم ولي الأمر مطلوب")
  .transform(squash)
  .pipe(
    z
      .string()
      .min(3, "الاسم قصير جداً")
      .max(100, "الاسم طويل جداً")
      .refine((v) => NAME_CHARS.test(v), "الاسم يجب أن يحتوي على حروف فقط"),
  );

export const gradeSchema = z.enum(GRADES, {
  errorMap: () => ({ message: "اختر الصف الدراسي من القائمة" }),
});

/* ───────── Forms ───────── */

export const registerSchema = z.object({
  student_name: studentNameSchema,
  student_phone: phoneField("رقم هاتف الطالب"),
  guardian_name: guardianNameSchema,
  guardian_phone: phoneField("رقم ولي الأمر"),
  grade: gradeSchema,
});
export type RegisterInput = z.input<typeof registerSchema>;

export const studentUpdateSchema = z.object({
  student_name: studentNameSchema,
  guardian_name: guardianNameSchema,
  guardian_phone: phoneField("رقم ولي الأمر"),
  grade: gradeSchema,
});
export type StudentUpdateInput = z.input<typeof studentUpdateSchema>;

/** Proof paths are generated by the server only: yyyy/mm/uuid.ext */
export const PROOF_PATH_RE = /^\d{4}\/\d{2}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$/;

const paymentBase = z.object({
  student_name: studentNameSchema,
  student_phone: phoneField("رقم هاتف الطالب"),
  sender_number: z.string().trim().optional().default(""),
  grade: gradeSchema,
  paid: z.boolean({ required_error: "اختر حالة الدفع" }),
  proof_path: z.string().trim().nullable().optional(),
});

type SenderFields = { paid: boolean; sender_number?: string };

function senderRule(val: SenderFields, ctx: z.RefinementCtx) {
  const sender = val.sender_number ? normalizePhone(val.sender_number) : "";
  if (val.paid && !sender) {
    ctx.addIssue({ code: "custom", path: ["sender_number"], message: "الرقم الذي تم التحويل منه مطلوب" });
  } else if (sender && !isValidPhone(sender)) {
    ctx.addIssue({ code: "custom", path: ["sender_number"], message: "رقم الهاتف غير صحيح. مثال: 01012345678" });
  }
}

function proofRule(val: { paid: boolean; proof_path?: string | null }, ctx: z.RefinementCtx) {
  if (val.paid && !val.proof_path) {
    ctx.addIssue({ code: "custom", path: ["proof"], message: "صورة الدفع مطلوبة" });
  } else if (val.paid && val.proof_path && !PROOF_PATH_RE.test(val.proof_path)) {
    ctx.addIssue({ code: "custom", path: ["proof"], message: "صورة الدفع غير صالحة" });
  }
}

/** Field-level checks used in the browser BEFORE the proof image is uploaded. */
export const paymentFieldsSchema = paymentBase.omit({ proof_path: true }).superRefine(senderRule);

/** Full server-side schema (includes the proof path issued by the server). */
export const paymentSchema = paymentBase
  .superRefine(senderRule)
  .superRefine(proofRule)
  .transform((val) => ({
    ...val,
    sender_number: val.sender_number ? normalizePhone(val.sender_number) : null,
    proof_path: val.paid ? (val.proof_path ?? null) : null,
  }));
export type PaymentInput = z.input<typeof paymentSchema>;

export const adminLoginSchema = z.object({
  identifier: z.string().trim().min(3, "أدخل اسم المستخدم").max(120),
  password: z.string().min(1, "أدخل كلمة المرور").max(200),
});

export const paymentStatusSchema = z.enum(["pending", "paid", "rejected"]);

/** First error message per field, for form display. */
export function fieldErrorsOf(error: z.ZodError): Record<string, string> {
  const out: Record<string, string> = {};
  for (const issue of error.issues) {
    const key = String(issue.path[0] ?? "form");
    if (!out[key]) out[key] = issue.message;
  }
  return out;
}

/** Client-side file check (server re-checks size + magic bytes). */
export function validateProofFile(file: File): string | null {
  const allowed = ["image/jpeg", "image/png", "image/webp"];
  if (!allowed.includes(file.type)) return "الملف يجب أن يكون صورة بصيغة JPG أو PNG أو WEBP";
  if (file.size > 5 * 1024 * 1024) return "حجم الصورة يجب ألا يتجاوز 5 ميجابايت";
  if (file.size === 0) return "الملف فارغ";
  return null;
}
